### ISSUE TITLE
Doesn't seem to work for me

### ISSUE THREAD

**Issue by kellerman** [Edveika/Swedbank-OEM-Bypass#1]
Hello. I have a similar setup.
KernelSU, Shamiko, Zygisk for Shamiko to work. MicroG (revived installer).
Play and SafetyNet integrity is fine (I didn't use the fix).
The prop already reports 0 and NFC payments still dont work (have never worked for a long time). Also Swedbank notifications doesn't work for me either.

**Comment by edveikis** [comment]
Hello,

What ROM are you using?

What error message does the Swedbank's app show?

Are you using the Swedbank's app to do NFC payments?

Are you spoofing the prop in some other way? Because if you have your bootloader unlocked it should return 1

When I used MicroG push notifications didn't work for me too, not sure how to fix it.

Edit: I remember there being an option in MicroG settings app that had something to do with push notifications, try playing around with it.

**Comment by kellerman** [comment]
I am now using Superiour Extended. But I have used many different ROMS before with the same problem.
Xiaomi Redmi K20 Pro. I have tried everything over time, including your method, but still Swedbank doesn't allow payments with cards. Biometry doesnt work.

About notifications:
App shows standard message, that it can't turn on notifications. Loading failed or something like that. With one different ROM Swedbank push notifications worked fine, maybe due to MicroG version. Now I am using the latest MicroG.
I even tried using the official Google Play store, because Aurora store can't pass the Play integrity checks, since SafetyNet is now depreceated.

Maybe there are some device specific things, that can't be or isn't properly spoofed.
I was very suprised seeing that you have managed to get the app working by editing this prop.

**Comment by edveikis** [comment]
What message does it show? Because if it shows that root is detected, this is a different issue. If the message says bootloader, this method should work. Try rebooting, force closing the Swedbank app and then do everything mentioned in the guide again.

You can see this message when you open the app and go to the cards section(i think you also have to click on the card and try to enable nfc payments)

In regards to hardware, I doubt that there is anything that prevents you from spoofing bootloader unlocked flag, my device is newer and I was able to do it.

**Comment by kellerman** [comment]
With previous installations (ROMS) it was always the error about OEM unlocking, but I tried cleaning cache, reinstalling the app after switching the toggle manually. No dice.
There is LSPosed module https://github.com/chiteroman/BootloaderSpoofer/releases which probably does the same. That didn't work either and there was the same OEM unlocking error. Root seemed to be properly hidden from the app, at least it didn't say anything about that.

Right now the app doesn't want to enable anything - biometry, mobile notifications and nfc payments. The app shows that the card doesn't support mobile payments. There isn't any warning about root or bootloader..

**Comment by edveikis** [comment]
> With previous installations (ROMS) it was always the error about OEM unlocking, but I tried cleaning cache, reinstalling the app after switching the toggle manually. No dice.
> There is LSPosed module https://github.com/chiteroman/BootloaderSpoofer/releases which probably does the same. That didn't work either and there was the same OEM unlocking error. Root seemed to be properly hidden from the app, at least it didn't say anything about that.
> 
> Right now the app doesn't want to enable anything - biometry, mobile notifications and nfc payments. The app shows that the card doesn't support mobile payments. There isn't any warning about root or bootloader..
> 

That's really strange. Using this method I was able to get it working, I guess you are on your own. Maybe it could have something to do with one of the modules that you have installed, but I have no clue. Good luck.

**Comment by kellerman** [comment]
I just set up another Google Pixel 6 with crDroid and MicroG. This time I used Magisk. Seems that Shamiko already sets the prop, thats why it reports 0 always. I use it in blacklist mode and enable it for specific apps, like SmartID and Swedbank. But the issues are exactly the same.
Maybe this works on Android 13, not 14 yet.
Do you use the latest MicroG and what installer did you use?

**Comment by edveikis** [comment]
I no longer use custom roms, but when i did i used this MicroG installer:

https://github.com/nift4/microg_installer_revived/releases/tag/v3.4.3-0

I dont think that it has anything to do with A14, though you could try it on A13 to make sure.
